### ISSUE TITLE
--root does not appear to work

### ISSUE THREAD

**Issue by grasmash** [hechoendrupal/drupal-console#2792]
I've attempted to run the following commands on RC5, all with the same result:

```
./vendor/bin/drupal --root=/Users/matthew.grasmick/Sites/blt/template/docroot
./vendor/bin/drupal --root=$(pwd)/docroot
./vendor/bin/drupal --root=./docroot
./vendor/bin/drupal --root=docroot
```

Output is: 

```
DrupalConsole must be executed within a Drupal Site.
 Try changing to a Drupal site directory and download it by executing:
 composer require drupal/console:~1.0 --prefer-dist --optimize-autoloader
```

However, executing within the `docroot` directory does work. It seems to me that `--root` should obviate the need for `cd`ing into the docroot, but it does not.

**Comment by jmolivas** [comment]
@grasmash can you try using the Drupal-Launcher the global executable ?

```
curl https://drupalconsole.com/installer -L -o drupal.phar
mv drupal.phar /usr/local/bin/drupal
chmod +x /usr/local/bin/drupal
```

**Comment by jerbob92** [comment]
@jmolivas It does work with Drupal-Launcher.
Why can't ```drupal/console/bin/drupal.php``` just use the path relative from it's own location instead of ```cwd``` though?
After that it's bootstrapped and then it will use ```--root```.

**Comment by jmolivas** [comment]
@grasmash @jerbob92 there is a PR I will merge including some fixes and will also make some improvements on the code to support this

**Comment by jerbob92** [comment]
@jmolivas nice! Which one is it?

**Comment by jmolivas** [comment]
@grasmash @jerbob92 This should be fixed with RC-6

**Comment by mickaelperrin** [comment]
@jmolivas Thanks for the patch, but sadly this still doesn't work for me.


In the drupal installation folder:

     www-data@ac680a14b75f:/src/web$ /src/vendor/bin/drupal --version
     Drupal Console version 1.0.0-rc6

In the home folder:

    www-data@ac680a14b75f:~$ /src/vendor/bin/drupal --version
     DrupalConsole must be executed within a Drupal Site.
     Try changing to a Drupal site directory and download it by executing:
     composer require drupal/console:~1.0 --prefer-dist --optimize-autoloader
 composer update drupal/console --with-dependencies

**Comment by jmolivas** [comment]
@Manjitsingh how did you installed?

**Comment by mickaelperrin** [comment]
@Jmolivas Are you talking to me ?

I installed and upgraded it with composer.

**Comment by mickaelperrin** [comment]
Just gave a look at the code and the `root` parameter seems to be broken by design as the script expects that `drupal` is launched from the drupal install dir before bootstrapping and reading the `root` parameter.

Is the solution proposed by @jerbob92 sufficient ? Should we provide a PR ?

**Comment by jmolivas** [comment]
@mickaelperrin a PR will be awesome.

**Comment by mickaelperrin** [comment]
@jmolivas a PR was provided to resolve this issue. Any return to quickly resolve this issue is welcome.

**Comment by bartvanhoutte** [comment]
I had an empty composer.json in a subproject which caused the error. After removing the empty file everything worked as designed. May I suggest adding a warning about having multiple composer.json files to the error?
