### ISSUE TITLE
Acquia blt + drupal vm + drupal console

### ISSUE THREAD

**Issue by annared** [hechoendrupal/drupal-console#2981]
I created a project with acquia blt + drupal vm.

i installed drupal console but it seems i can't make it works correcly:
if i use the `drupal list` command i get this error even if i am inside the drupal root directory:

`[WARNING] In order to list all of the available commands, you should run this inside a drupal root directory. `

**Comment by jmolivas** [comment]
@annared: Can you share your VM?

Can you confirm you have DrupalConsole installed on the site by executing from the site root:
```
composer show | grep drupal/console 
```

**Comment by jmolivas** [comment]
@annared can you try executing `composer update drupal/console`

There was an issue with https://github.com/webflo/drupal-finder a DC dependency and  https://github.com/acquia/lightning-project but was fixed already

**Comment by nilanjanray** [comment]
Hi @jmolivas, 

Same error for me as well, I have updated the beta-5 version to rc-10 using the composer update
currently new dependency added i.e. console-core & console-en. Now once try to execute ```drupal list``` from drupal root same as warning is showing as ```[WARNING] In order to list all of the available commands, you should run this inside a drupal root directory.```

Regards,
nilanjan

**Comment by nilanjanray** [comment]
Also there may have some break with dependency as if I try to run ```composer require drupal/console:1.0.0-rc10``` doesn't resolve the composer dependency with ```drupal/console-core & drupal/console-en```

**Comment by jmolivas** [comment]
@nilanjanray for updating dependencies of dependencies try:

```
composer update drupal/console --with-dependencies
```

**Comment by nilanjanray** [comment]
@jmolivas Thanks for your reply! I have tried with same, but unable to resolve the dependency ,
please take a look the attachment

![console](https://cloud.githubusercontent.com/assets/1309170/20912105/37c631f8-bb93-11e6-9fc6-376915980d95.png)

**Comment by jmolivas** [comment]
@annared @nilanjanray  Try instead

```
composer require drupal/console:~1.0 --no-update
composer update
```

**Comment by jmolivas** [comment]
This must be related to this https://github.com/hechoendrupal/DrupalConsole/issues/2905

**Comment by harold20** [comment]
I can't reproduce it in the version 1.9.0

**Comment by harold20** [comment]
How to configure a remote site using drupalVM https://github.com/geerlingguy/drupal-vm/pull/1943
