### ISSUE TITLE
[generate:entity:content] Error: Class 'SplFileInfo' does not have a method 'serialize'

### ISSUE THREAD

**Issue by thuiban** [hechoendrupal/drupal-console#4086]
### Problem/Motivation
When trying to generate a entity with the console runs into an error. That happens for every content type i'm trying to export.

Drupal version 8.7.2
Console version 1.9.0
Console Launcher version 1.9.0

### Error

`[ERROR] Warning: call_user_func_array() expects parameter 1 to be a valid callback,
class 'SplFileInfo' does not have a method 'serialize' in Drupal\Core\Extension\Extension->__call() (line 160
of core/lib/Drupal/Core/Extension/Extension.php).

Drupal\Core\Extension\Extension->__call('serialize', Array) (Line: 314)

Drupal\Console\Extension\Manager->createExtension(Object) (Line: 251)

Drupal\Console\Extension\Manager->getModule('palm_custom_module') (Line: 69)

Drupal\Console\Generator\EntityContentGenerator->generate(Array) (Line: 180)

Drupal\Console\Command\Generate\EntityContentCommand->execute(Object, Object) (Line: 255)

Symfony\Component\Console\Command\Command->run(Object, Object) (Line: 987)

Symfony\Component\Console\Application->doRunCommand(Object, Object, Object) (Line: 255)

Symfony\Component\Console\Application->doRun(Object, Object) (Line: 187)

Drupal\Console\Core\Application->doRun(Object, Object) (Line: 64)

Drupal\Console\Application->doRun(Object, Object) (Line: 148)

Symfony\Component\Console\Application->run() (Line: 89)

require('/var/www/html/vendor/drupal/console/bin/drupal.php') (Line: 4)

[ERROR] Warning: call_user_func_array() expects parameter 1 to be a valid callback,
class 'SplFileInfo' does not have a method 'unserialize' in Drupal\Core\Extension\Extension->__call() (line 160
of core/lib/Drupal/Core/Extension/Extension.php).

Drupal\Core\Extension\Extension->__call('unserialize', Array) (Line: 314)

Drupal\Console\Extension\Manager->createExtension(Object) (Line: 251)

Drupal\Console\Extension\Manager->getModule('palm_custom_module') (Line: 69)

Drupal\Console\Generator\EntityContentGenerator->generate(Array) (Line: 180)

Drupal\Console\Command\Generate\EntityContentCommand->execute(Object, Object) (Line: 255)

Symfony\Component\Console\Command\Command->run(Object, Object) (Line: 987)

Symfony\Component\Console\Application->doRunCommand(Object, Object, Object) (Line: 255)

Symfony\Component\Console\Application->doRun(Object, Object) (Line: 187)

Drupal\Console\Core\Application->doRun(Object, Object) (Line: 64)

Drupal\Console\Application->doRun(Object, Object) (Line: 148)

Symfony\Component\Console\Application->run() (Line: 89)

require('/var/www/html/vendor/drupal/console/bin/drupal.php') (Line: 4)
`
### Log

![](https://user-images.githubusercontent.com/16882863/59430754-626e5000-8de3-11e9-90ee-08de776bb29d.png)

I tried nothing yet

**Comment by srjosh** [comment]
Can confirm this issue as well. https://gist.github.com/6fed0efc723ba863b4c9888485316f9a

**Comment by harold20** [comment]
@thuiban @srjosh  We merged a PR https://github.com/hechoendrupal/drupal-console/pull/4013 that fixes the issues related with `SplFileInfo`. Could you try this in the dev environment? Here the doc how have a dev environment https://docs.drupalconsole.com/en/contributing/new-features.html. Otherwise we will release the 1.9.1 version in a couple weeks.

**Comment by ccjjmartin** [comment]
I can confirm that the changes in PR #4013 are included in my local environment (running 1.9.0) and that the errors are still present, also running Drupal Core 8.6.16

**Comment by gilbertomangones** [comment]
Hi, the mentioned error no longer exists. I did the following test:
Starting from a newly installed Drupal 8.7.7 

**Using**
 Drupal                    8.7.7
Console                   1.9.3

**Testing**

1. After to run the command ```$ drupal generate:entity:content```, display the next "Warning":
 [WARNING] It looks like you have a hook_theme already declared                                                                                                                                           
           **Please manually merge the two hook_theme() implementations in                                                
           modules/custom/testentity/testentity.module**
2. This Warning, although it shows error on the website and applying the warning suggestion, it is corrected o deleted the following lines.
![2019-09-27_1721](https://user-images.githubusercontent.com/6983125/65805485-5ec0c800-e14b-11e9-839b-aba981c3bbc2.png)


3. Reviewing the new entity created, but, its not appear in admin/structure. is necessary **clear cache**. ```$ drupal cr all``` that to appear. for my case:
4. Appears two links, 
     Test1 type (this works fine). 
     Test1 List: generate a error
 (**“The website encountered an unexpected error. Please try again later.”**)

![2019-09-27_1716](https://user-images.githubusercontent.com/6983125/65805377-d9d5ae80-e14a-11e9-9fd4-215d4b2bb408.png)

5. The error is the following:

"Drupal\Core\Database\DatabaseExceptionWrapper: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'testdrupal8v2.test1' doesn't exist: SELECT COUNT(*) AS expression FROM (SELECT 1 AS expression FROM {test1} base_table GROUP BY base_table.vid, base_table.id) subquery; Array ( ) in Drupal\Core\Entity\EntityListBuilder->getEntityIds() (line 104 of /Applications/XAMPP/xamppfiles/htdocs/testdrupal8v2/web/core/lib/Drupal/Core/Entity/EntityListBuilder.php)."

Attachment image.

![test1](https://user-images.githubusercontent.com/6983125/65805355-bca0e000-e14a-11e9-9250-573925fb9b5b.png)
![test2](https://user-images.githubusercontent.com/6983125/65805356-bd397680-e14a-11e9-8a90-df22fbb91093.png)
![test3](https://user-images.githubusercontent.com/6983125/65805357-bd397680-e14a-11e9-9e95-4e1f61f27f35.png)

Thank's

**Comment by enzolutions** [comment]
Thanks @gilbertomangones for testing
